SELECT * FROM RATING
CREATE OR REPLACE PROCEDURE edit_rating ( model_id IN NUMBER, user_id IN NUMBER, rate IN NUMBER)
IS
BEGIN
	UPDATE RATING
	SET RATING = rate
	WHERE MODEL_COLOR_ID = model_id AND  CUSTOMER_ID = user_id;
END;