CREATE OR REPLACE PROCEDURE update_order_state( order_id1 IN NUMBER, state IN VARCHAR2 )
IS 

BEGIN 
	UPDATE ORDERLIST
	SET ORDER_STATE = state
	WHERE ORDER_ID = order_id1;
EXCEPTION 
	WHEN OTHERS THEN 
			DBMS_OUTPUT.PUT_LINE('INSERTION NOT DONE');
END;