CREATE OR REPLACE PROCEDURE update_order_state( order_id1 IN NUMBER, state IN VARCHAR2 )
IS 
	pt VARCHAR2(15);
BEGIN 
	UPDATE ORDERLIST
	SET ORDER_STATE = state
	WHERE ORDER_ID = order_id1;

	SELECT PAYMENT_METHOD INTO pt
	FROM ORDERLIST
	WHERE ORDER_ID = order_id1;

	IF pt = 'COD' THEN 
		UPDATE ORDERLIST
		SET PAYMENT_STATUS = 'PAID'
		WHERE ORDER_ID = order_id1;
	END IF;

EXCEPTION 
	WHEN OTHERS THEN 
			DBMS_OUTPUT.PUT_LINE('INSERTION NOT DONE');
END;