CREATE OR REPLACE FUNCTION sales_in_month ( comp_id IN NUMBER )
RETURN NUMBER IS
	total NUMBER;
BEGIN
	total := 0;
	FOR R IN ( SELECT *
             FROM ORDERLIST O1
             JOIN CART CA1 USING (CART_ID)
             JOIN CARS C1 USING ( MODEL_COLOR_ID ) 
						 WHERE C1.COMPANY_ID = comp_id AND (O1.ORDER_DATE BETWEEN TRUNC(SYSDATE, 'MM') AND ADD_MONTHS(TRUNC(SYSDATE, 'MM'),1)) )
	LOOP
		total := R.CAR_COUNT*R.PRICE + total;
	END LOOP;
	
	DBMS_OUTPUT.PUT_LINE(total);
	RETURN total;
END;