CREATE OR REPLACE TRIGGER  update_confirm_status
AFTER INSERT
ON orderlist
FOR EACH ROW
DECLARE
BEGIN 
	UPDATE CART cart
	SET cart.CONFIRM_STATUS = 'CONFIRMED'
	WHERE cart.CART_ID = :NEW.CART_ID;
EXCEPTION 
	WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('NO DATA found TO update');
	WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('OTHERS IN DELETE');
END;
/